spring.application.name=CadastroDeNinjas

# Define o caminho para acessar o console
spring.h2.console.path=/h2-console

# Cria a URL de conexão do banco
spring.datasource.url=${DATABASE_URL}

# Define o driver correto para o H2
spring.datasource.driver=org.h2.Driver

# Define o usuário padrão
spring.datasource.username=${DATABASE_USERNAME}

# Deixa a senha vazia (padrão do H2)
spring.datasource.password=${DATABASE_PASSWORD}

# Configurações do JPA // HIBERNATES
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Habilita o console do H2 no navegador
spring.h2.console.enabled=true

# Configurar o flyway
spring.flyway.enable=true
spring.flyway.locations=classpath:db/migrations
spring.flyway.baseline-on-migrate=true
